// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/yuliang/protobuf_rpc/proto/BusinessServiceProto.proto

package com.yuliang.protobuf_rpc.proto;

public final class BusinessService {
  private BusinessService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code BusinessServiceProto}
   */
  public static abstract class BusinessServiceProto
      implements com.google.protobuf.Service {
    protected BusinessServiceProto() {}

    public interface Interface {
      /**
       * <code>rpc buy(.BusinessRequestProto) returns (.BusinessResponseProto);</code>
       */
      public abstract void buy(
          com.google.protobuf.RpcController controller,
          com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request,
          com.google.protobuf.RpcCallback<com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BusinessServiceProto() {
        @java.lang.Override
        public  void buy(
            com.google.protobuf.RpcController controller,
            com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request,
            com.google.protobuf.RpcCallback<com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto> done) {
          impl.buy(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.buy(controller, (com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc buy(.BusinessRequestProto) returns (.BusinessResponseProto);</code>
     */
    public abstract void buy(
        com.google.protobuf.RpcController controller,
        com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request,
        com.google.protobuf.RpcCallback<com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.yuliang.protobuf_rpc.proto.BusinessService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.buy(controller, (com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto)request,
            com.google.protobuf.RpcUtil.<com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.yuliang.protobuf_rpc.proto.BusinessService.BusinessServiceProto implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void buy(
          com.google.protobuf.RpcController controller,
          com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request,
          com.google.protobuf.RpcCallback<com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.class,
            com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto buy(
          com.google.protobuf.RpcController controller,
          com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto buy(
          com.google.protobuf.RpcController controller,
          com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:BusinessServiceProto)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9com/yuliang/protobuf_rpc/proto/Busines" +
      "sServiceProto.proto\0322com/yuliang/protobu" +
      "f_rpc/proto/BusinessProto.proto2L\n\024Busin" +
      "essServiceProto\0224\n\003buy\022\025.BusinessRequest" +
      "Proto\032\026.BusinessResponseProtoB7\n\036com.yul" +
      "iang.protobuf_rpc.protoB\017BusinessService" +
      "\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yuliang.protobuf_rpc.proto.Business.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
