// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/yuliang/protobuf_rpc/proto/BusinessProto.proto

package com.yuliang.protobuf_rpc.proto;

public final class Business {
  private Business() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BusinessRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string brand = 1;
    /**
     * <code>required string brand = 1;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    // required int64 num = 2;
    /**
     * <code>required int64 num = 2;</code>
     */
    boolean hasNum();
    /**
     * <code>required int64 num = 2;</code>
     */
    long getNum();

    // required double price = 3;
    /**
     * <code>required double price = 3;</code>
     */
    boolean hasPrice();
    /**
     * <code>required double price = 3;</code>
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code BusinessRequestProto}
   */
  public static final class BusinessRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements BusinessRequestProtoOrBuilder {
    // Use BusinessRequestProto.newBuilder() to construct.
    private BusinessRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BusinessRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BusinessRequestProto defaultInstance;
    public static BusinessRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public BusinessRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              brand_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num_ = input.readInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              price_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.class, com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<BusinessRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<BusinessRequestProto>() {
      public BusinessRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BusinessRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string brand = 1;
    public static final int BRAND_FIELD_NUMBER = 1;
    private java.lang.Object brand_;
    /**
     * <code>required string brand = 1;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private long num_;
    /**
     * <code>required int64 num = 2;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 num = 2;</code>
     */
    public long getNum() {
      return num_;
    }

    // required double price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    /**
     * <code>required double price = 3;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double price = 3;</code>
     */
    public double getPrice() {
      return price_;
    }

    private void initFields() {
      brand_ = "";
      num_ = 0L;
      price_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, price_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto)) {
        return super.equals(obj);
      }
      com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto other = (com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto) obj;

      boolean result = true;
      result = result && (hasBrand() == other.hasBrand());
      if (hasBrand()) {
        result = result && getBrand()
            .equals(other.getBrand());
      }
      result = result && (hasNum() == other.hasNum());
      if (hasNum()) {
        result = result && (getNum()
            == other.getNum());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (Double.doubleToLongBits(getPrice())    == Double.doubleToLongBits(other.getPrice()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBrand()) {
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + getBrand().hashCode();
      }
      if (hasNum()) {
        hash = (37 * hash) + NUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getNum());
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getPrice()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BusinessRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.class, com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.Builder.class);
      }

      // Construct using com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessRequestProto_descriptor;
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto getDefaultInstanceForType() {
        return com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.getDefaultInstance();
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto build() {
        com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto buildPartial() {
        com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto result = new com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto) {
          return mergeFrom((com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto other) {
        if (other == com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrand()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yuliang.protobuf_rpc.proto.Business.BusinessRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string brand = 1;
      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 1;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      // required int64 num = 2;
      private long num_ ;
      /**
       * <code>required int64 num = 2;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 num = 2;</code>
       */
      public long getNum() {
        return num_;
      }
      /**
       * <code>required int64 num = 2;</code>
       */
      public Builder setNum(long value) {
        bitField0_ |= 0x00000002;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 num = 2;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0L;
        onChanged();
        return this;
      }

      // required double price = 3;
      private double price_ ;
      /**
       * <code>required double price = 3;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double price = 3;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>required double price = 3;</code>
       */
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double price = 3;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BusinessRequestProto)
    }

    static {
      defaultInstance = new BusinessRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BusinessRequestProto)
  }

  public interface BusinessResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string result = 1;
    /**
     * <code>required string result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>required string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code BusinessResponseProto}
   */
  public static final class BusinessResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements BusinessResponseProtoOrBuilder {
    // Use BusinessResponseProto.newBuilder() to construct.
    private BusinessResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BusinessResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BusinessResponseProto defaultInstance;
    public static BusinessResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public BusinessResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              result_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.class, com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.Builder.class);
    }

    public static com.google.protobuf.Parser<BusinessResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<BusinessResponseProto>() {
      public BusinessResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessResponseProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BusinessResponseProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.lang.Object result_;
    /**
     * <code>required string result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto)) {
        return super.equals(obj);
      }
      com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto other = (com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BusinessResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.class, com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.Builder.class);
      }

      // Construct using com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yuliang.protobuf_rpc.proto.Business.internal_static_BusinessResponseProto_descriptor;
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto getDefaultInstanceForType() {
        return com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance();
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto build() {
        com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto buildPartial() {
        com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto result = new com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto) {
          return mergeFrom((com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto other) {
        if (other == com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto.getDefaultInstance()) return this;
        if (other.hasResult()) {
          bitField0_ |= 0x00000001;
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yuliang.protobuf_rpc.proto.Business.BusinessResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string result = 1;
      private java.lang.Object result_ = "";
      /**
       * <code>required string result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>required string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BusinessResponseProto)
    }

    static {
      defaultInstance = new BusinessResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BusinessResponseProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BusinessRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BusinessRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BusinessResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BusinessResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2com/yuliang/protobuf_rpc/proto/Busines" +
      "sProto.proto\"A\n\024BusinessRequestProto\022\r\n\005" +
      "brand\030\001 \002(\t\022\013\n\003num\030\002 \002(\003\022\r\n\005price\030\003 \002(\001\"" +
      "\'\n\025BusinessResponseProto\022\016\n\006result\030\001 \002(\t" +
      "B0\n\036com.yuliang.protobuf_rpc.protoB\010Busi" +
      "ness\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BusinessRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BusinessRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BusinessRequestProto_descriptor,
              new java.lang.String[] { "Brand", "Num", "Price", });
          internal_static_BusinessResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BusinessResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BusinessResponseProto_descriptor,
              new java.lang.String[] { "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
